#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MapsAndLocationDemo.Resource", IsApplication=true)]

namespace MapsAndLocationDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monkey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int polarbear = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public const int ScrollView01 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int addressTextView = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int animateButton = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int demoLocationServices = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int locationTextView = 2130968577;
			
			// aapt resource value: 0x7f04000c
			public const int map = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int mapWithOverlay = 2130968589;
			
			// aapt resource value: 0x7f040007
			public const int showMapWithOverlays = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int showMapsApp = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int showSampleMapActivity = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int showStreetView = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int text = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int zoomInButton = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int zoomOutButton = 2130968586;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LocationView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MapLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MapWithOverlayLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050007
			public const int activity_label_location = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int activity_label_mapwithmarkers = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int activity_label_samplemap = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int app_name = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int demoLocationServices = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int mapsAppText = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int showMapActivity = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int showMapWithOverlays = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int streetViewText = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Bubble_TextAppearance_Dark = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Bubble_TextAppearance_Light = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ClusterIcon_TextAppearance = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
